### ISSUE TITLE
Port Yii2 to Yii3 questions.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/db-redis#12]
This operative db-redis, connection and active-record I have the following proposals.

- [x] Leave this package only with the connection, like most db implementations, like db-sqlite for example.
- [x] Move the active-record from db-redis to yiisoft / active-record, so it is always guaranteed that the active-record is never broken, since all the tests will be executed there, they will be called RedisActiveRecord, RedisActiveQuery.
- [x] As for the cache and sessions, they can be left here or implemented in each package, in cache and sessions, and only the connection is injected, which is simple now.

@samdark @yiisoft/yii3

I await your comments.

**Comment by samdark** [comment]
> Move the active-record from db-redis to yiisoft / active-record, so it is always guaranteed that the active-record is never broken, since all the tests will be executed there, they will be called RedisActiveRecord, RedisActiveQuery.

Moving AR stuff to AR layer is fine but it should not be the same package for DB, Redis, Mongo etc.

**Comment by samdark** [comment]
Overall the idea is fine.

**Comment by terabytesoftw** [comment]
> > Move the active-record from db-redis to yiisoft / active-record, so it is always guaranteed that the active-record is never broken, since all the tests will be executed there, they will be called RedisActiveRecord, RedisActiveQuery.
> 
> Moving AR stuff to AR layer is fine but it should not be the same package for DB, Redis, Mongo etc.

The idea of AR is to create a Redis folder, where ActiveRecord will go, and ActiveQuery for Redis, they will depend on ConnectionInterface, and it will work without problems like the other drivers, just install Db-Redis and ActiveRecord.
