### ISSUE TITLE
The ActiveQuery and Connection inheritance of DB-Redis is also the YII \ Base \Component of Yii2

### ISSUE THREAD

**Issue by qiangcxq** [yiisoft/db-redis#7]
`There is no inheritance`
![1](https://user-images.githubusercontent.com/28077952/86733040-72e30f80-c063-11ea-9fcd-4d00b4f074fb.png)
![2](https://user-images.githubusercontent.com/28077952/86733053-770f2d00-c063-11ea-962f-09b49e4b0689.png)

**Comment by samdark** [comment]
This package is work in progress. It was imported but actual code wasn't done yet.
